defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Conversion
markdown:         kramdown
highlighter:      rouge

# Markdown Processor
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

url: https://bees.bagbatch.co.uk
timezone: GMT

# Permalinks
permalink: none


exclude: ["book", "presentation", "*.synctex.gz", "*.sh", "Vagrantfile"]
include: ["queens"]