version: '3'
services:
    docs:
        image: jekyll/jekyll:latest
        environment: 
            JEKYLL_VERSION: 3.8
        container_name: rhapsody-angel-docs
        volumes:
            - ./:/srv/jekyll
        ports:
            - '8089:4000'
        command: jekyll serve --watch --force_polling